version: '3'
services:
  calories-counting-frontend:
    build:
      context: ./frontend
      dockerfile: frontend.Dockerfile
    ports:
      - "3000:80"
    networks:
      - app-network

  calories-counting-api:
    build:
      context: ./CaloriesApi
      dockerfile: api.Dockerfile 
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
